Add psr-7 response support
OskarStark/symfony-http-responder pull request #11
Opened 2021-03-22 20:04 UTC by kpicaza

Related to issue https://github.com/OskarStark/symfony-http-responder/issues/10.

- [x] PSR-7 ResponseInterface support
- [x] Unit tests
- [x] Docs

2021-03-22 20:32 UTC, azjezz commented on README.md
> +    public function __invoke(RequestHandlerInterface $request): ResponseInterface
```suggestion
    public function handle(RequestHandlerInterface $request): ResponseInterface
```

2021-03-22 20:34 UTC, azjezz commented on composer.json
> +        "psr/http-server-handler": "Allows using PSR-7 response responder.",
this should be removed, not needed.

2021-03-22 20:34 UTC, azjezz commented on composer.json
> +        "nyholm/psr7": "PSR-7 Request and Response implementation.",
this is suggested by the bridge, should be removed.

2021-03-22 20:45 UTC, azjezz commented on src/Psr7Responder.php
> +    ): ResponseInterface {
```suggestion
    public function render(
        string $template,
        array $context = [],
        int $status = Response::HTTP_OK,
        array $headers = []
    ): ResponseInterface {
```
```suggestion
    public function render(string $template, array $context = [], int $status = Response::HTTP_OK, array $headers = []): ResponseInterface {
```

let's keep this file consistent with `Responder` ( no line break in arguments ), or change it in the other file too.

2021-03-22 20:50 UTC, azjezz commented on README.md
> +```
this is the configuration for the bridge, i don't think we should include it here, it's already documented.

2021-03-22 20:50 UTC, azjezz commented on README.md
> +```
same for this.

2021-03-23 15:48 UTC, azjezz commented on README.md
> +    public function handle(RequestHandlerInterface $request): ResponseInterface
#[Route] annotation should be moved to the method i suppose?

2021-03-23 15:50 UTC, azjezz approved these changes
👍

2021-03-23 16:33 UTC, azjezz commented
@OskarStark i think you should remove the requirement for PHP 8.1 tests to pass in order to merge, as dependencies don't install and i can't merge it 😅

2021-03-24 07:36 UTC, OskarStark commented
> @OskarStark i think you should remove the requirement for PHP 8.1 tests to pass in order to merge, as dependencies don't install and i can't merge it 😅

I thought the same 😃

2021-03-24 07:37 UTC, OskarStark commented
Done

2021-03-24 07:38 UTC, OskarStark commented on README.md
> +use Psr\Http\Message\ServerRequestInterface;
unused

2021-03-24 07:38 UTC, OskarStark commented on README.md
> +use Psr\Http\Message\ServerRequestInterface;
unused

2021-03-24 07:39 UTC, OskarStark commented on README.md
> +use Psr\Http\Message\ServerRequestInterface;
unused

2021-03-24 07:39 UTC, OskarStark commented on README.md
> +use Psr\Http\Message\ServerRequestInterface;
unused

2021-03-24 07:39 UTC, OskarStark commented on README.md
> +use Psr\Http\Message\ServerRequestInterface;
unused

2021-03-24 07:40 UTC, OskarStark commented on src/Psr7Responder.php
> +     * Render the given twig template and return an HTML response.
```suggestion
     * Render the given Twig template and return an HTML response.
```

2021-03-24 07:40 UTC, OskarStark requested changes
Some minor comments

2021-03-24 16:27 UTC, kpicaza commented on README.md
> +use Psr\Http\Message\ServerRequestInterface;
Thanks ;- D, it is a copy/paste mistake, it is used but it has the wrong type in the readme. It should be:

````php
use OskarStark\Symfony\Http\Psr7Responder;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Symfony\Component\Routing\Annotation\Route;

final class RedirectHandler implements RequestHandlerInterface
{
    public function __construct(
        private Psr7Responder $responder,
    ) {
    }

    #[Route('/redirect', name: 'app_redirect')]
-    public function handle(RequestHandlerInterface $request): ResponseInterface // wrong parameter typehint
+    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->responder->route('app_my_route');
    }
}

````

Fixing it ;-)

2021-03-24 21:10 UTC, OskarStark approved these changes

2021-03-24 21:11 UTC, merged